// AUTO-GENERATED by scripts/gen-soar-types.ts — DO NOT EDIT BY HAND.
// Source: FortiSOAR widgetServiceAPI contenthub docs (v8.0.0).
// Regenerate: pnpm gen-types   (cross-checked against fsr_src/app.unmin.js)
//
// These ambient declarations type the SOAR platform services a widget may
// inject. Used by the harness's own TS and (Phase 3) by an opt-in checkJs
// pass over widget source. Param NAMES come from the docs; types are the
// documented ngdoc types mapped to TS (unknown where undocumented).

declare namespace Soar {
  /** The appModulesService loads application modules and provides state information from module names. */
  interface AppModulesService {
    checkViolations(rejection: object, attributes?: unknown[], isConfigurationManager?: boolean): void;
    getListState(moduleName: string): void;
    getModules(modules: unknown[]): unknown[];
    getQueueModules(): Promise<unknown>;
    getState(moduleName: string): string;
    load(excludeSystemModule?: boolean, forceReload?: boolean): Promise<unknown>;
  }
  /** The AuthenticationConfig service handles API requests to gather configuration options. */
  interface AuthenticationConfig {
    // No methods documented for this service.
    [key: string]: unknown;
  }
  /** The AuthenticationService handles submitting credentials, NFA, and logout. */
  interface AuthenticationService {
    // No methods documented for this service.
    [key: string]: unknown;
  }
  /** The commonUtils service contains commonly used functions. */
  interface CommonUtils {
    copyToClipboard(fields: object, row?: object, col?: object, rows?: object): void;
    generateUUID(): string;
    isBase64Image(value: string): boolean;
    isJinja(value: string): boolean;
    isNumber(value: object): boolean;
    isObject(value: object): boolean;
    isUUID(s: string): boolean;
    isUndefined(value: object): boolean;
    isValidURL(value: string): boolean;
    parseJSON(str: string): object;
    searchInJSON(jsonObj: object, searchText: string): object;
  }
  /** The purpose of the service is to handle connector-specific operations like creating connectors, getting connector details, etc. */
  interface ConnectorService {
    deleteConnector(id: string): Promise<unknown>;
    executeConnectorAction(connectorName: string, connectorVersion: string, operation: string, configuration: string, params: object, audit?: boolean, auditInfo?: object, agent?: string): Promise<unknown>;
    getConnector(name: string, version: string, agent?: string): Promise<unknown>;
    getConnectorHealth(connector: object, configUUID: string, agent?: string): Promise<unknown>;
    getDevelopedConnector(id: string, editRepoConnector?: boolean): Promise<unknown>;
    updateConnectorConfig(connector: object, newConfig: boolean, deleteConfig: boolean): Promise<unknown>;
  }
  /** The purpose of the currentPermissionsService is to get module specific permission details. */
  interface CurrentPermissionsService {
    availableFieldPermission(module: unknown[], fieldName: unknown[], action: string): boolean;
    availablePermission(module: string, action: string): boolean;
    availablePermissions(modules: unknown[], action: string): unknown[];
    get(): object;
    getPermission(module: string): object;
    getPermissions(modules: unknown[]): object;
    isAdmin(): boolean;
  }
  /** The editorLanguageService handles the language server functionality to communicate with the language server for providing IntelliSense in the Editor. */
  interface EditorLanguageService {
    closeEditor(): void;
    closeLangSocket(): void;
    connectLangSocket(): void;
    createAndListenOnLangSocket(): void;
    initMonacoEditorService(): void;
  }
  /** The Entity service is a prototyped object that represents a module and all of its metadata and fields. Handles loading and population of data based on permissions, module name, and id. Takes care of a */
  interface Entity {
    applyDefaultValues(): void;
    delete(): Promise<unknown>;
    evaluate(query: object): object;
    evaluateAllFields(): void;
    get(id: string, userParams?: object, ignoreErrors?: boolean, refresh?: boolean): Promise<unknown>;
    getEmptyRequiredFields(): unknown[];
    getEmptyRequiredFieldsObject(): object;
    getExportData(): Promise<unknown>;
    getFieldTitles(): unknown[];
    getFormFields(sorted?: boolean): object;
    getFormFieldsArray(): unknown[];
    getFormFieldsArrayWithoutSystem(): unknown[];
    getFormFieldsWithoutSystem(): object;
    getRelationship(fieldName: string, getObjects?: boolean, recordSize?: unknown, columns?: unknown[]): Promise<unknown>;
    getRelationshipFields(): object;
    getRelationshipFieldsArray(): unknown[];
    hasEmptyRequiredFields(): boolean;
    loadAllRelationships(): Promise<unknown>;
    loadFields(mode?: string, ignoreRBAC?: boolean): Promise<unknown>;
    save(data: object, params?: object, fieldsToKeep?: unknown[]): Promise<unknown>;
  }
  /** The exportService handles copying, exporting, and downloading playbooks */
  interface ExportService {
    changePlaybookAndStepsUuid(playbook: object, uuidPlaybookMap: object, replaceAllUuids: boolean, collectionClone: boolean, existingOutsideCollection: boolean): void;
    copyEntities(entities: unknown[], entityName: string, userParams?: boolean): unknown[];
    downloadJsonFile(data: object, fileName: string): void;
    exportGridRecords(route: string, params: object): Promise<unknown>;
    getMacrosFromPlaybook(playbook: object, variables: boolean): unknown[];
    getReferencePlaybookForExport(playbooks: object, includeVersions: boolean): Promise<unknown>;
    loadCollectionNames(): Promise<unknown>;
    loadCollectionPlaybooks(collection: object): Promise<unknown>;
    loadRowsForExport(rows: unknown[], entityName: string): Promise<unknown>;
    saveNewMacrosFromPlaybook(macros: unknown[]): Promise<unknown>;
  }
  /** The Field service is an object that represents the model of a field. */
  interface Field {
    evaluateRequired(entity: object): void;
    evaluateVisible(entity: object): void;
    getFormValue(): string;
  }
  /** The FormEntityService handles entity related operation like set, get and submit fields. */
  interface FormEntityService {
    get(): object;
    set(newEntity: object): void;
  }
  /** The licenseService gets and sets license details. */
  interface LicenseService {
    getBrandingDetails(latest?: boolean): Promise<unknown>;
    getLicenseDetails(reload?: boolean, includeNodes?: boolean): Promise<unknown>;
  }
  /** The modelMetadatasService loads model metadata and retrieves information from it. */
  interface ModelMetadatasService {
    getIriByType(type: string): string;
    getMetadataByModuleType(type: string): string;
    getModuleList(): Promise<unknown>;
    getModuleNameByType(moduleTypes: unknown[], isPlural: boolean): unknown[];
    getTenantModuleList(tenantUuid?: string): Promise<unknown>;
    getTenantStaggingModule(tenantUuid: string, moduleUuid: string): Promise<unknown>;
    loadAllModules(forceUpdate?: boolean): Promise<unknown>;
    publishTenant(tenantUuid: string): Promise<unknown>;
  }
  /** The Modules service is simply a wrapper for ng.$resource and adds update. Optionally accepts module, id, and fieldName */
  interface Modules {
    save(config: object, params: object): Promise<unknown>;
  }
  /** PagedCollection service creates objects that work against the paged crud-hub API. This is the base class that other PagedCollection child classes would use. */
  interface PagedCollection {
    buildSortQuery(sortColumns: unknown[]): void;
    convertToKeyPairs(): Promise<unknown>;
    extendFilter(_config: object, value: object, field: object): void;
    gotoPage(params: object): Promise<unknown>;
    load(customQuery?: object, customColumns?: unknown[], relationshipKey?: boolean): Promise<unknown>;
    loadByPost(config: object, sortApplied?: boolean): Promise<unknown>;
    loadDefaultColumns(relationshipKey?: string, mergeDefaults?: boolean): object;
    loadGridRecord(config?: object, sortApplied?: boolean, getAllColumns?: boolean, recordId?: unknown, associationField?: string, csvNeutralization?: boolean): Promise<unknown>;
    pageFirst(loadByPost: boolean): Promise<unknown>;
    pageLast(loadByPost: boolean): Promise<unknown>;
    pageNext(loadByPost: boolean): Promise<unknown>;
    pagePrevious(loadByPost: boolean): Promise<unknown>;
    setPage(data: object): Promise<unknown>;
    sortColumnsByFieldName(direction: string): void;
  }
  /** The picklistsService will facilitate performing actions in regards gathering and manipulating picklists. */
  interface PicklistsService {
    getPicklistByIri(iri: string): Promise<unknown>;
    getPicklistByItemValue(field: unknown, itemValue: string): Promise<unknown>;
    loadAllPicklists(useExport?: boolean): Promise<unknown>;
    loadPicklistsByParams(itemVal: string, itemKey: string): Promise<unknown>;
  }
  /** The purpose of the playbookService is to perform playbook related operation like get playbook details, create playbook, get playbook execution log details etc. */
  interface PlaybookService {
    getPlaybookExecutionCount(): Promise<unknown>;
    getRunningPlaybookDetails(id: string): Promise<unknown>;
    getRunningPlaybooks(query: object): Promise<unknown>;
    getStepRunningDetails(id: string): Promise<unknown>;
  }
  /** The PromiseQueue service stores, retrieves, and clears promises so they can be shared instead of doing the same work multiple times. This is very useful when making API calls in quick succession when  */
  interface PromiseQueue {
    clear(): void;
    get(key: string): Promise<unknown>;
    set(key: string, promise: Promise<unknown>): void;
  }
  /** The Query service provides an object that represents API query parameters and filters and exposes methods for manipulating and retrieving data about them. */
  interface Query {
    buildOrderForPostRequest(entity: object, queryParam: object): void;
    getFlatQuery(entity?: object): object;
    getQuery(useValue?: boolean, dataMode?: string): object;
    getQueryModifiers(entity?: object): object;
    updateFilter(filter: object, type: string): object;
    updateFilters(filters: unknown[]): void;
  }
  /** The queryCollectionService loads, saves, manipulates, and deletes query collections, etc.. */
  interface QueryCollectionService {
    load(model: string, storeTime: unknown): Promise<unknown>;
    loadQueryFilterValues(query: unknown): Promise<unknown>;
    loadResource(iri: string): Promise<unknown>;
  }
  /** The settingsService gets and sets user and system settings. */
  interface SettingsService {
    get(key: string): string;
    getSystem(): Promise<unknown>;
  }
  /** The tokenService handles idle and session timers, and provides methods for manipulating and getting information from JWT web tokens. */
  interface TokenService {
    get(): string;
    set(token: string): void;
  }
  /** The usersService is an auxiliary service that performs actions regarding users. It includes methods for interacting with the current user and updating DAS users. */
  interface UsersService {
    getAvatar(avatarIri: string): Promise<unknown>;
    getCurrentAvatar(): Promise<unknown>;
    getCurrentUser(): object;
    getUserByIri(userIri: string): Promise<unknown>;
    loadCurrentUser(): Promise<unknown>;
  }
  /** The ViewTemplateService loads and saves view templates. */
  interface ViewTemplateService {
    changeStructure(structure: number, currentColumns: unknown[], objectName: string): unknown[];
    get(page: string): Promise<unknown>;
    getConditionalVisibilityFilteredData(): void;
    populateConditionalFields(): void;
  }
  /** The websocketService handles the websocket functionality to update the UI and backend with live data */
  interface WebsocketService {
    disconnect(logout: boolean): void;
    generateWebsocketSessionId(): string;
    getHeader(): string;
    getWebsocketSessionId(): string;
    openSocket(): Promise<unknown>;
    reconnect(): void;
    subscribe(topic: string, callback: unknown): Promise<unknown>;
    unsubscribe(subscription: unknown): void;
  }
  /** The widgetTemplateService loads widget definition. */
  interface WidgetTemplateService {
    generateWidgetDefinition(widget: object): object;
  }

  /** Maps the name a widget injects -> that service's interface. */
  interface ServiceMap {
    appModulesService: AppModulesService;
    AuthenticationConfig: AuthenticationConfig;
    AuthenticationService: AuthenticationService;
    CommonUtils: CommonUtils;
    connectorService: ConnectorService;
    currentPermissionsService: CurrentPermissionsService;
    editorLanguageService: EditorLanguageService;
    Entity: Entity;
    exportService: ExportService;
    Field: Field;
    FormEntityService: FormEntityService;
    licenseService: LicenseService;
    modelMetadatasService: ModelMetadatasService;
    Modules: Modules;
    PagedCollection: PagedCollection;
    picklistsService: PicklistsService;
    playbookService: PlaybookService;
    PromiseQueue: PromiseQueue;
    Query: Query;
    queryCollectionService: QueryCollectionService;
    settingsService: SettingsService;
    tokenService: TokenService;
    usersService: UsersService;
    ViewTemplateService: ViewTemplateService;
    websocketService: WebsocketService;
    widgetTemplateService: WidgetTemplateService;
  }
}
